### ISSUE TITLE
Display unresponsive on wake

### ISSUE THREAD

**Issue by andreacremaschi** [mkernel/EWProxyFramebuffer#1]
Hi Enno,

it seems that there is an issue with EWProxyFrameBuffer and wake on sleep. This has been observed at least by me and another user (fernlightning), on Lion (iMac) and Mountain Lion GM.
When the kext is installed, the display is frozen when the OS wakes up from sleep: the mouse cursor no longer moves and the display doesn't update.

Fernlighting reports:
"unplugging, replugging display makes no difference.
There are no errors in the system logs.
Can ssh in and reboot."

Removing the kext and rebooting fixes the sleep issue.

rif. andreacremaschi/Syphon-virtual-screen#3

a.c.

**Comment by mkernel** [comment]
Hi Andrea,

I will have a look into it.

Greetings,
Enno

Am 02.08.2012 um 11:49 schrieb Andrea Cremaschi reply@reply.github.com:

**Comment by mkernel** [comment]
@andreacremaschi the fix from e6d6632 should fix the issue. I wasn't able to reproduce the problem on 10.9 with this fix. So you should have a look. I'll close this issue but comment on your issue.
I'm very sorry for the delay...

**Comment by andreacremaschi** [comment]
Thank you! I'll give it a try. :beer:

**Comment by andreacremaschi** [comment]
I can confirm that this is resolved now!
